### ISSUE TITLE
Consider splitting up into multiple packages

### ISSUE THREAD

**Issue by krisrok** [hextantstudios/com.hextantstudios.utilities#1]
Hey and thanks for your work. The Settings framework is pretty great and a joy to use.

Problem is, I do not want to convolute my own package with a dependency on your whole utilities package when I'd only need the Settings stuff. I guess I'll just stick with a custom settings implementation for now. 

Maybe consider splitting it up into different packages so it can be used in a more modular way.

**Comment by Hextant** [comment]
Sorry for the delay getting back to you. I didn't have my GitHub watch settings set how I thought.

I plan to add a few more things to this repository over time and they will definitely depend on other things that I write before. I just don't have the time to split each new thing out and duplicate / re-test all the code. If there's enough interest, then I may be able to move out just the settings stuff at some point though.

**Comment by krisrok** [comment]
I've been working on some new features in my [serialization branch](https://github.com/krisrok/com.hextantstudios.utilities/commits/serialization), mainly about (de)serializing settings for the build to allow for quick changes via overrides. I may have gone a bit overboard, some parts are heavily refactored and I'm not yet super happy with some of it. Feel free to have a look!

Would you be ok with me moving the settings part into a new package and new namespace?

New namespace because in some projects I'd like to add your package for the other parts but I still want to be able to use my settings codebase without conflicts.

On the other hand, when using the settings package as a dependency for other packages (to just add a few settings) I'd not want to add other functionality like the selection history and compile time logs -- even though they're pretty useful.

**Comment by Hextant** [comment]
@krisrok Sounds interesting! I'll try to take a look this week. 

This repo is [CC BY 4.0 licensed](https://creativecommons.org/licenses/by/4.0/) so you can change whatever and merge it with your code however you'd like as long as you follow the two terms there. To give attribution you can just have a comment like the following:
```cs
// Derivative of "https://github.com/hextantstudios/com.hextantstudios.utilities" 
//   Original Copyright 2021 by Hextant Studios. https://HextantStudios.com
//   Used under CC BY 4.0. http://creativecommons.org/licenses/by/4.0/
```

**Comment by krisrok** [comment]
Thanks for your clear advice! Will do.

I'll try to add some usage examples for the changed stuff otherwise it might be hard to grasp what changed (and why).

**Comment by Hextant** [comment]
Sounds good!
