### ISSUE TITLE
OpenUPM Support

### ISSUE THREAD

**Issue by Fijo** [hextantstudios/com.hextantstudios.utilities#4]
I'd like to use this package using openupm. I've already added it there.
Could you please create a new Tag v0.1.0 since that's the version that's currently specified in the package.json.

Also in the future I'd be awesome if you added a new tag each time the version in the package.json changes.

That way people could use this project without having to use git to include it into unity.
https://openupm.com/packages/com.hextantstudios.utilities/

Optionally, it might also be cool to refer people to openupm as well in the README.md so they are aware that's an option too.

Thanks in advance!

**Comment by Hextant** [comment]
I updated the version to v0.1.1 with a small fix for the SelectionHistory. See if that will work. 
I've updated the Readme locally to include a link to OpenUPM, but haven't pushed it yet.

**Comment by Fijo** [comment]
I've just tested it and it's working nicely. Thanks for your help!
